site_name: Algorithmic Modeling Special Training
use_directory_urls: false

copyright: Copyright &copy; 2021 Fernando Ferraz Ribeiro

theme:
  features:
    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  

site_url: "https://255ribeiro.github.io/algorithmic_modeling_special_training/"
repo_url: "https://github.com/255ribeiro/algorithmic_modeling_special_training/"
repo_name: "255ribeiro/algorithmic_modeling_special_training" 

nav:
  - Home: index.md
  
  - Rhino3D: 
      - Install: Rhino_3D_Training\rh_install\install_rhino.md
      - Interface: Rhino_3D_Training\rh_inter\rh_inter.md
      - Aliases: Rhino_3D_Training\rh_aliases\aliases.md
      - Curves basics: Rhino_3D_Training\rh_curves_basics\curves_basics.md
      - Surfaces and Breps: Rhino_3D_Training\rh_Srf_brep\rh_srf_brep.md
      - Modeling execise: Rhino_3D_Training\rh_modeling_example\rh_modeling_example.md

  - Grasshopper:
      - Introduction: Grasshopper_Training\grass_intro.md
      - Interface: Grasshopper_Training\gh_interface\gh_inter.md
      - Sliders: Grasshopper_Training\Slider\Slider_config.md
      - Panels: Grasshopper_Training\Panels\Painel_config.md
      - Exercise- Sequence of Columns: Grasshopper_Training\gh_pilares\gh_pilares.md
      - Lists Basics: Grasshopper_Training\gh_list_intro\gh_list_basics.md
      - Exercise Multiple floor buildings: Grasshopper_Training\gh_multi_pav\gh_multi_pav.md
      - Planes and vectors: Grasshopper_Training\gh_vect_plane\vect_plane_basics.md
      - Morph: Grasshopper_Training\gh_morph\gh_morph.md
      - Profiles: Grasshopper_Training\profiles\profiles.md

  - Python:
      - Install: Python_Training\intro_py\instala.md
      - Extra configuration: Python_Training\intro_py\extra_config.md
      - frist steps: Python_Training\intro_py\intro_py.md
      - Spyder IDE intro: Python_Training\cientif_py\spyder_intro.md
      - Variables an Operators: Python_Training\intro_py\variaveis_e_operadores.ipynb
      - Basic examples:
            - Fisrt program: Python_Training\intro_py\python_example\first_program.py
            - While: Python_Training\intro_py\python_example\loop_while.py
            - For: Python_Training\intro_py\python_example\for_loop.py
            - Guess the number game: Python_Training\intro_py\python_example\guess_the_number.ipynb
      - List examples:
            - Example 01: Python_Training\intro_py\python_example\list_examples.py
            - Example 02: Python_Training\intro_py\python_example\list_example_02.py
            - Example 03: Python_Training\intro_py\python_example\list_example_03.py
      - Data structures: Python_Training\intro_py\datastructures.ipynb
      - File handeling: Python_Training\intro_py\file_handeling.ipynb
      - Jupyter notebooks: Python_Training\cientif_py\jupyter_intro.ipynb
      - numpy: Python_Training\cientif_py\numpy_intro.ipynb
      - matplotlib: Python_Training\cientif_py\matplotlib_intro.ipynb
      - scipy: Python_Training\cientif_py\scipy_intro.ipynb
      - pandas: Python_Training\dados_py\pandas_intro.ipynb
      - Geopandas: Python_Training\geo_py\geopandas.md
      - Google Earth Engine:
            - Introduction and instalation: Python_Training\geo_py\geemap.md
            - Frist Steps: Python_Training\geo_py\geemap_intro.ipynb
  - References: ref/ref.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter:
      #execute: True
      include_source: True


extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/255ribeiro
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCCkMaRdD7PBWhs4JgH5s6_w
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/
      - icon: fontawesome/solid/envelope-square
        link: mailto:ffribeiro@gmail.com